# Use the official .NET SDK for building the project
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY ["WebAPI/WebAPI.csproj", "WebAPI/"]
RUN dotnet restore "WebAPI/WebAPI.csproj"

COPY ["WebAPI/", "WebAPI/"]
RUN dotnet build "WebAPI/WebAPI.csproj" -c Release -o /build

FROM build as publish
RUN dotnet publish "WebAPI/WebAPI.csproj" -c Release -o /publish

# Use the ASP.NET Core runtime to run the app
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
EXPOSE 5000
ENTRYPOINT ["dotnet", "WebAPI.dll"]